export const APP_ROLES = [
  'ADMIN',
  'HR',
  'ACCOUNTANT',
  'PROJECT_MANAGER',
  'ASSET_CUSTODIAN',
  'DEPARTMENT_HEAD',
  'AUDITOR',
  'EMPLOYEE',
] as const

export type AppRole = (typeof APP_ROLES)[number]
export type ScopeMode = 'NONE' | 'ALL' | 'ASSIGNED' | 'SELF'

export const ROLE_LABELS: Record<AppRole, string> = {
  ADMIN: 'Администратор',
  HR: 'Кадровик',
  ACCOUNTANT: 'Бухгалтер',
  PROJECT_MANAGER: 'Руководитель проекта',
  ASSET_CUSTODIAN: 'Материально ответственное лицо',
  DEPARTMENT_HEAD: 'Руководитель подразделения',
  AUDITOR: 'Аудитор',
  EMPLOYEE: 'Сотрудник',
}

export const PERMISSIONS = [
  'departments.read',
  'departments.create',
  'departments.update',
  'departments.delete',
  'access.users.read',
  'access.users.create',
  'access.users.update',
  'access.assignments.read',
  'access.assignments.create',
  'access.assignments.update',
  'access.assignments.delete',
  'employees.read',
  'employees.create',
  'employees.update',
  'employees.delete',
  'staffSchedule.read',
  'staffSchedule.create',
  'staffSchedule.update',
  'staffSchedule.delete',
  'vacations.read',
  'vacations.create',
  'vacations.update',
  'vacations.delete',
  'personnelActions.read',
  'personnelActions.create',
  'personnelActions.delete',
  'personnelActions.sync',
  'projects.read',
  'projects.reference.read',
  'projects.create',
  'projects.update',
  'projects.delete',
  'projectMembers.read',
  'projectMembers.create',
  'projectMembers.update',
  'tasks.read',
  'tasks.create',
  'tasks.update',
  'tasks.delete',
  'timekeeping.read',
  'timekeeping.create',
  'timekeeping.update',
  'timekeeping.delete',
  'finance.salary.read',
  'financePlans.read',
  'financePlans.create',
  'financePlans.update',
  'financePlans.delete',
  'projectPayroll.read',
  'projectPayroll.create',
  'projectPayroll.update',
  'projectPayroll.delete',
  'payroll.read',
  'payroll.manage',
  'payroll.close',
  'payroll.export',
  'assets.read',
  'assets.create',
  'assets.update',
  'assets.delete',
  'assets.transfer',
  'assets.dispose',
  'assets.archive',
  'assets.restore',
  'assets.export',
  'assetGroups.read',
  'assetGroups.create',
  'assetGroups.update',
  'assetGroups.delete',
  'mols.read',
  'mols.create',
  'mols.update',
  'mols.delete',
  'operations.read',
  'documents.read',
  'documents.create',
  'documents.update',
  'documents.archive',
  'documents.download',
  'approvals.read',
  'approvals.create',
  'approvals.decide',
  'approvals.cancel',
  'account.password.update',
  'auditLogs.read',
] as const

export type Permission = (typeof PERMISSIONS)[number]

type ScopeKind = 'none' | 'department' | 'employee' | 'project' | 'finance' | 'asset' | 'document'

export const PERMISSION_SCOPE: Record<Permission, ScopeKind> = {
  'departments.read': 'department',
  'departments.create': 'none',
  'departments.update': 'department',
  'departments.delete': 'department',
  'access.users.read': 'none',
  'access.users.create': 'none',
  'access.users.update': 'none',
  'access.assignments.read': 'none',
  'access.assignments.create': 'none',
  'access.assignments.update': 'none',
  'access.assignments.delete': 'none',
  'employees.read': 'employee',
  'employees.create': 'department',
  'employees.update': 'employee',
  'employees.delete': 'employee',
  'staffSchedule.read': 'department',
  'staffSchedule.create': 'department',
  'staffSchedule.update': 'department',
  'staffSchedule.delete': 'department',
  'vacations.read': 'employee',
  'vacations.create': 'employee',
  'vacations.update': 'employee',
  'vacations.delete': 'employee',
  'personnelActions.read': 'employee',
  'personnelActions.create': 'employee',
  'personnelActions.delete': 'employee',
  'personnelActions.sync': 'department',
  'projects.read': 'project',
  'projects.reference.read': 'none',
  'projects.create': 'none',
  'projects.update': 'project',
  'projects.delete': 'project',
  'projectMembers.read': 'project',
  'projectMembers.create': 'project',
  'projectMembers.update': 'project',
  'tasks.read': 'project',
  'tasks.create': 'project',
  'tasks.update': 'project',
  'tasks.delete': 'project',
  'timekeeping.read': 'none',
  'timekeeping.create': 'none',
  'timekeeping.update': 'none',
  'timekeeping.delete': 'none',
  'finance.salary.read': 'finance',
  'financePlans.read': 'finance',
  'financePlans.create': 'finance',
  'financePlans.update': 'finance',
  'financePlans.delete': 'finance',
  'projectPayroll.read': 'project',
  'projectPayroll.create': 'project',
  'projectPayroll.update': 'project',
  'projectPayroll.delete': 'project',
  'payroll.read': 'none',
  'payroll.manage': 'none',
  'payroll.close': 'none',
  'payroll.export': 'none',
  'assets.read': 'asset',
  'assets.create': 'department',
  'assets.update': 'department',
  'assets.delete': 'department',
  'assets.transfer': 'department',
  'assets.dispose': 'department',
  'assets.archive': 'department',
  'assets.restore': 'department',
  'assets.export': 'asset',
  'assetGroups.read': 'none',
  'assetGroups.create': 'none',
  'assetGroups.update': 'none',
  'assetGroups.delete': 'none',
  'mols.read': 'department',
  'mols.create': 'department',
  'mols.update': 'department',
  'mols.delete': 'department',
  'operations.read': 'asset',
  'documents.read': 'document',
  'documents.create': 'document',
  'documents.update': 'document',
  'documents.archive': 'document',
  'documents.download': 'document',
  'approvals.read': 'none',
  'approvals.create': 'none',
  'approvals.decide': 'none',
  'approvals.cancel': 'none',
  'account.password.update': 'none',
  'auditLogs.read': 'none',
}

const crud = (resource: string) => [
  `${resource}.read`,
  `${resource}.create`,
  `${resource}.update`,
  `${resource}.delete`,
] as Permission[]

const businessReads = PERMISSIONS.filter((permission) =>
  permission.endsWith('.read') &&
  !permission.startsWith('access.') &&
  permission !== 'account.password.update'
)

export const ROLE_PERMISSIONS: Record<AppRole, ReadonlySet<Permission>> = {
  ADMIN: new Set(PERMISSIONS),
  HR: new Set([
    'departments.read',
    ...crud('employees'),
    ...crud('staffSchedule'),
    ...crud('vacations'),
    'personnelActions.read',
    'personnelActions.create',
    'personnelActions.delete',
    'personnelActions.sync',
    ...crud('timekeeping'),
    'documents.read',
    'documents.create',
    'documents.update',
    'documents.archive',
    'documents.download',
    'approvals.read',
    'approvals.create',
    'approvals.decide',
    'approvals.cancel',
    'account.password.update',
  ]),
  ACCOUNTANT: new Set([
    'departments.read',
    'projects.read',
    'projectMembers.read',
    'finance.salary.read',
    ...crud('financePlans'),
    ...crud('projectPayroll'),
    'payroll.read',
    'payroll.manage',
    'payroll.close',
    'payroll.export',
    'timekeeping.read',
    'documents.read',
    'documents.create',
    'documents.update',
    'documents.download',
    'approvals.read',
    'approvals.create',
    'approvals.decide',
    'approvals.cancel',
    'account.password.update',
  ]),
  PROJECT_MANAGER: new Set([
    'projects.read',
    'projects.create',
    'projects.update',
    'projects.delete',
    'projectMembers.read',
    'projectMembers.create',
    'projectMembers.update',
    ...crud('tasks'),
    ...crud('timekeeping'),
    'assets.read',
    'operations.read',
    'documents.read',
    'documents.create',
    'documents.update',
    'documents.archive',
    'documents.download',
    'approvals.read',
    'approvals.create',
    'approvals.decide',
    'approvals.cancel',
    'account.password.update',
  ]),
  ASSET_CUSTODIAN: new Set([
    'departments.read',
    'projects.reference.read',
    ...crud('assets'),
    'assets.transfer',
    'assets.dispose',
    'assets.archive',
    'assets.restore',
    'assets.export',
    ...crud('assetGroups'),
    ...crud('mols'),
    'operations.read',
    'documents.read',
    'documents.create',
    'documents.update',
    'documents.archive',
    'documents.download',
    'approvals.read',
    'approvals.create',
    'approvals.decide',
    'account.password.update',
  ]),
  DEPARTMENT_HEAD: new Set([
    'departments.read',
    'employees.read',
    'staffSchedule.read',
    'vacations.read',
    'personnelActions.read',
    'projects.read',
    'projectMembers.read',
    'tasks.read',
    'timekeeping.read',
    'timekeeping.create',
    'timekeeping.update',
    'timekeeping.delete',
    'assets.read',
    'assets.export',
    'mols.read',
    'operations.read',
    'documents.read',
    'documents.download',
    'approvals.read',
    'approvals.create',
    'approvals.decide',
    'approvals.cancel',
    'account.password.update',
  ]),
  AUDITOR: new Set([
    ...businessReads,
    'assets.export',
    'auditLogs.read',
    'documents.download',
    'payroll.export',
    'approvals.read',
    'account.password.update',
  ]),
  EMPLOYEE: new Set([
    'departments.read',
    'employees.read',
    'vacations.read',
    'personnelActions.read',
    'projects.read',
    'projectMembers.read',
    'tasks.read',
    'timekeeping.read',
    'timekeeping.create',
    'timekeeping.update',
    'timekeeping.delete',
    'finance.salary.read',
    'documents.read',
    'documents.download',
    'approvals.read',
    'approvals.create',
    'approvals.cancel',
    'account.password.update',
  ]),
}

export const DEFAULT_ROLE_SCOPES: Record<
  AppRole,
  { departmentScopeMode: ScopeMode; projectScopeMode: ScopeMode }
> = {
  ADMIN: { departmentScopeMode: 'ALL', projectScopeMode: 'ALL' },
  HR: { departmentScopeMode: 'ASSIGNED', projectScopeMode: 'NONE' },
  ACCOUNTANT: { departmentScopeMode: 'ASSIGNED', projectScopeMode: 'ASSIGNED' },
  PROJECT_MANAGER: { departmentScopeMode: 'NONE', projectScopeMode: 'ASSIGNED' },
  ASSET_CUSTODIAN: { departmentScopeMode: 'ASSIGNED', projectScopeMode: 'NONE' },
  DEPARTMENT_HEAD: { departmentScopeMode: 'ASSIGNED', projectScopeMode: 'ASSIGNED' },
  AUDITOR: { departmentScopeMode: 'ALL', projectScopeMode: 'ALL' },
  EMPLOYEE: { departmentScopeMode: 'SELF', projectScopeMode: 'SELF' },
}

export const roleHasPermission = (role: AppRole, permission: Permission) =>
  ROLE_PERMISSIONS[role].has(permission)
